---
title: "sleepDep"
author: "Maria T"
date: "March 3, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
library(tidyverse)
library(lattice)
library(lme4)
library(arm)
library(pbkrtest)
```


### Descriptive Statistics

```{r}
sleep <- read.delim("~/Desktop/MSc BioInf/2nd sem/statistics/sleep.txt")
```


### Spaghetti Plot

```{r, echo=T}
interaction.plot(sleep$Days,sleep$Subject,sleep$Reaction,xlab="days", ylab="reaction time",legend=F, col="black")
```


### Summary

```{r,echo=T}
sleepMean<-tapply(sleep$Reaction,sleep$Days,mean)
sleepSD<-tapply(sleep$Reaction,sleep$Days,sd)
sleepVar<-tapply(sleep$Reaction,sleep$Days,var)
sleep.n<-table(sleep$Days)
descriptive<-cbind(sleepMean,sleepSD,sleepVar,sleep.n)
```


### Observed Mean

```{r,echo=F}
interaction.plot(sleep$Days,sleep$Subject,sleep$Reaction,xlab="days", ylab="reaction time",legend=F, col="grey")
lines(c(0:9),sleepMean,col="red")
```


### Mean evolution (with 1 SE intervals)

```{r,echo=T}
errbar=function(x,y,height,width,lty=1,col="black"){
  arrows(x,y,x,y-height,angle=90,length=width,lty=lty,col=col)
  arrows(x,y,x,y-height,angle=90,length=width,lty=lty,col=col)
}
plot(c(0:9),descriptive[,1],type="b",xlim=c(0,10),ylim=c(100,500),xlab="Days",ylab="Reaction Time",axes=T,main="Mean evolution (with 1 SE intervals)")
axis(side=1,at=c(0:9),labels=c(0:9))
axis(side=2,at=seq(200,450,50))
box()
errbar(c(0:9),descriptive[,1],descriptive[,2],.1,col = "red")
```


### Boxplots

```{r,echo=T}
boxplot(sleep$Reaction~sleep$Days,xlab="days",ylab = "reaction time")
```


### Hierarchical model
```{r,echo=T}
sleep.reshaped<-reshape(sleep,timevar = "Days",idvar = "Subject", direction = "wide")
correlationSleep<-cor(sleep.reshaped[,2:11])
cf<-sapply(sleep$Subject, function(x) coef(lm(sleep$Reaction~sleep$Days, data=subset(sleep, Subject==x))))
Sx<-reorder(sleep$Subject, cf[1,])
xyplot(sleep$Reaction ~ sleep$Days|Sx,data=sleep,type=c('p','r'),auto.key=T,aspect="xy", par.settings=list(axis.text=list(cex=0.6), fontsize=list(text=8, points=10)),scales=list( x=list(at=c(0:9),labels=c("0","1","2","3","4","5","6","7","8","9"))),xlab = "days",ylab = "reaction time")
```

```{r,echo=F}
lin.reg.coef<-by(sleep,Subject,function(data) coef(lm(Reaction~Days,data=data)))
lin.reg.coef1<-unlist(lin.reg.coef)
names(lin.reg.coef1)<-NULL
lin.reg.coef2=matrix(lin.reg.coef1,length(lin.reg.coef1)/2,2,byrow =TRUE)
```


### Histograms

```{r,echo=F}
lin.reg.r.squared <- by(sleep, Subject,function(data) summary(lm(Reaction~Days, data=data))$r.squared)
lin.reg.r.squared1<- as.vector(unlist(lin.reg.r.squared))
par(mfrow=c(3,1))
hist(lin.reg.coef2[,1],xlab="Intercept",col="lightblue",main="Histogram of individual intercepts")
hist(lin.reg.coef2[,2],xlab="Slope",col="lightblue",main="Histogram of individual slopes")
hist(lin.reg.r.squared1,xlab="R squared",col="lightblue",main="Histogram of individual R squared")
```


### Fitting the model(Marginal Model)

```{r,echo=T}
sleep.lmer1<-lmer(Reaction~1+Days+(1+Days|Subject), data=sleep)
summary(sleep.lmer1)
```


### Testing the fixed effects 

```{r,echo=F}
confint(sleep.reml,  par=5:6, method='Wald', oldNames=F)
confint(sleep.reml, method='boot', boot.type='perc', oldNames=F, nsim=500)
confint(sleep.reml, level=0.95, method='profile',   oldNames=F)
```







